server:
  port: 8100


resilience4j.retry:
  instances:
    currency-conversion-api:
#      maxRetryAttempts: 5 # @Deprecated
      maxAttempts: 5
      waitDuration: 5s
      enableExponentialBackoff: true

#    default:
#      maxRetryAttempts: 6  # @Deprecated
#      maxAttempts: 5
#      waitDuration: 1s
#      enableExponentialBackOff: true

resilience4j.circuitbreaker:
  instances:
    default:
      failureRateThreshold: 90

resilience4j.ratelimit:
  instances:
    default: # can be replaced with name - currency-conversion-api
        limitForPeriod: 2
        limitRefreshPeriod: 10s

resilience4j.bulkhead:
  instances:
    default:
      maxConcurrentCalls: 10


spring:
  application:
    name: currency-conversion-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      profile: dev    # Profile changes without this property

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      # default-zone: naming-server:8761/eureka

  instance:
    prefer-ip-address: true
    ip-address: localhost  # or use actual IP
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

# Tracing, Logs, and Metrics - For Spring Boot 3
management:
  tracing:
    sampling:
      probability: 1.0      # 1.0 means, we want to trace every requests

logging:
  patter:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"      # Format




