server:
  port: 8000

spring:
  application:
    name: currency-exchange

  config:
    import: optional:configserver:http://localhost:8888

  sql:
    init:
      mode: always

  datasource:
#    url: jdbc:mysql://localhost:3306/currency_exchange_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    url: jdbc:mysql://localhost:3336/currency_exchange_service
    username: maniraj
    password: Alliswell@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    defer-data-source-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      allowPublicKeyRetrieval: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

resilience4j:
  retry:
    instances:
      currency-exchange-get-all:
        maxRetryAttempts : 5

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


